### ISSUE TITLE
DM-ng not part of spec

### ISSUE THREAD

**Issue by grodansparadis** [grodansparadis/vscp-ux#10]
DM-ng is not part of the spec and should not be available as this is official. Maybe later but I don't see the need right now.

**Comment by BlueAndi** [comment]
I know, DM-NG has only RFC status ... hmmm ... I will move it, but would be good to keep it here as long as possible. Lets move it out just before the next release. That makes the maintenance easier for me at the moment.

BTW if you think about it again ... it wouldn't be necessary to have now events (all lamps on / off) just to be able to trigger the standard DM, because its not able to compare data.

**Comment by grodansparadis** [comment]
Den 2015-11-25 kl. 16:45, skrev Andreas Merkle:
>
> I know, DM-NG has only RFC status ... hmmm ... I will move it, but 
> would be good to keep it here as long as possible. Lets move it out 
> just before the next release. That makes the maintenance easier for me 
> at the moment.
>
Just don't want in there in the release code if it's not "standard".  
But OK for now.

> BTW if you think about it again ... it wouldn't be necessary to have 
> now events (all lamps on / off) just to be able to trigger the 
> standard DM, because its not able to compare data.
>

I understand fully what you are after. But the problem is that if we 
start to "understand" data formats in the data part we are into 
comparing values etc also.  IMO this is best done in the actions. If 
this is started there will always be one case more that should go int 
the matrix. And I want to keep it KISS. For actions they can be as 
complex as implementors want.

But that said I will have a look at this again. It is good. That is not 
the problem. But my worries is just what it starts.

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
I understand you as well. The problem I see is with poeple who don't want to change someone else code (actions) only to be able to trigger something. They want just buy a hardware at your shop, configure it and use it.

Maybe a solution which follows KISS as well would be to provide a domain specific language like IFTT, or openHAB to configure the DM-NG. The result can be programmed to the node. GREAT! This is an idea I have in mind ...

**Comment by grodansparadis** [comment]
Yes users should not need to change any code.  Nothing I do is built 
with that in mind. I can assure you. A lot of people will miss 
functionality on any module nevertheless, it does not matter how much 
functionality you build in. People come up with new ways. But I try to 
have a functionality that is simple. This happens - then do that. Easy 
to use. Easy to set up. And yes people will still have problems with it. 
Folks  that want to do other things have to go elsewhere. Its the same 
with everything. But I listen at needs and try to adopt.  Or make 
another module that meet that need.

I want to keep Level I small and tiny and simple so it works on small 
and tiny and simple devices. Level II is an other thing though. Lua and 
other things can run there (as I plan to have in the daemon DM) on nodes 
and there is a lot of opportunities for a lot of things.  The focus for 
new things should go there not on Level I IMHO.

The buy, configure, and run is in the higher level code today. Still, 
even with your work we are on the same level with a developer 
perspective.  I don't want end users to know about registers and DM. 
They should be on a much higher level with a much harder abstraction to 
hide the things on lower levels.

/Ake

Den 2015-11-25 kl. 21:26, skrev Andreas Merkle:
>
> I understand you as well. The problem I see is with poeple who don't 
> want to change someone else code (actions) only to be able to trigger 
> something. They want just buy a hardware at your shop, configure it 
> and use it.
>
> Maybe a solution which follows KISS as well would be to provide a 
> domain specific language like IFTT, or openHAB to configure the DM-NG. 
> The result can be programmed to the node. GREAT! This is an idea I 
> have in mind ...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp-ux/issues/10#issuecomment-159723366>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org
