### ISSUE TITLE
Check the wizard

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp-ux#6]
please check the wizard (see services) with some nodes and their mdf

notes:
- all recipe related keywords are not fully supported right now
- only the "important" mdf tags are supported yet

**Comment by grodansparadis** [comment]
Will do (need to get the release out first).

Den 2015-11-03 kl. 21:03, skrev Andreas Merkle:
>
> please check the wizard (see services) with some nodes and their mdf
>
> notes:
>
>   * all recipe related keywords are not fully supported right now
>   * only the "important" mdf tags are supported yet
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp-ux/issues/6>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by grodansparadis** [comment]
Hmmmm... I am unable to load the MDF from a remote location. Do I have to do something special?

**Comment by grodansparadis** [comment]
BTW Good job. Everything looks so neat and nice now!  Time to switch in the distributed demo also for the next release.

**Comment by BlueAndi** [comment]
Probably the remote download doesn't work because of CORS! You will see this only in the browser debugger. Update the server header via .htaccess to allow it and it will work.

Because yesterday my second daughter was born, any VSCP work is stopped at the moment.

**Comment by grodansparadis** [comment]
Den 2015-11-19 kl. 23:29, skrev Andreas Merkle:
>
> Probably the remote download doesn't work because of CORS! You will 
> see this only in the browser debugger. Update the server header via 
> .htaccess to allow it and it will work.
>
OK I will check that.


> Because yesterday my second daughter was born, any VSCP work is 
> stopped at the moment.
>
Big congratulations man. That is a great thing and a great time. So yes 
work should be stopped if you have your priorities sorted. Enjoy this 
time, soon they fly out and away from you. It happens so fast. Congrats 
again. Well done! :)

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
Thanks!

**Comment by BlueAndi** [comment]
Got some time ... did you check the probably CORS problem?

**Comment by grodansparadis** [comment]
Sadly I haven't had time to go further with it.  As it looks now not until next week. On my knees....
