### ISSUE TITLE
Change copyright

### ISSUE THREAD

**Issue by grodansparadis** [grodansparadis/vscp-ux#8]
Page copyright should probably be "VSCP team" or something instead of Grodans Paradis AB

**Comment by BlueAndi** [comment]
You mean the copyright notes on every html file in the footer?
If we write "VSCP team", where will be described who is in the team?

**Comment by grodansparadis** [comment]
I used to have "VSCP Team" before on most stuff but removed it as there 
is not much of a team. That page is here 
<http://www.vscp.org/wiki/doku.php/the_vscp_team?s[]=vscp&s[]=team>

Could be updated I guess.  With you second.

/Ake

Den 2015-11-25 kl. 16:39, skrev Andreas Merkle:
>
> You mean the copyright notes on every html file in the footer?
> If we write "VSCP team", where will be described who is in the team?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp-ux/issues/8#issuecomment-159644053>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org
